export const lootArrayArmadura = [
  "Armadura Sagrada",
  "Armadura Precaria",
  "Armadura Mitológica",
  "Armadura Forjada",
  "Armadura de Hielo",
  "Armadura de Fuego",
  "Armadura de Viento",
  "Armadura de Tierra",
  "Armadura de Vdjamër",
  "Armadura Renacida",
  "Armadura de Cristal",
  "Armadura del Pantano",
  "Armadura Inmortal",
  "Armadura Infinita",
  "Armadura del Bosque",
  "Armadura de la Tormenta",
  "Armadura del Dolor",
  "Armadura de Combate",
  "Armadura Magica",
  "Armadura Sideral",
  "Armadura Legendaria",
  "Armadura Precaria",
  "Armadura Oscura",
  "Armadura del Clavel",
  "Armadura de M'shong",
  "Armadura de Förh",
  "Armadura de Himmelzelt",
  "Armadura de Tundra",
  "Armadura del Ciclope",
  "Armadura de Piedra",
  "Armadura de Ceniza",
  "Armadura Única de Bolthemert",
  "Armadura de Hielo Seco",
  "Armadura de 8bits",
  "Armadura Eterna y No Muerta",
  "Armadura Muerta",
  "Armadura Pesada",
  "Armadura de Combate de Worther",
  "Armadura Epica",
  "Armadura Usada",
  "Armadura Vieja",
  "Armadura Básica",
  "Armadura Rústica",
];
export const lootArrayArma = [
  "Arma Sagrada",
  "Arma Precaria",
  "Arma Mitológica",
  "Arma Forjada",
  "Arma de Hielo",
  "Arma de Fuego",
  "Arma de Viento",
  "Arma de Tierra",
  "Arma de Vdjamër",
  "Arma Renacida",
  "Arma de Cristal",
  "Arma del Pantano",
  "Arma Inmortal",
  "Arma Infinita",
  "Arma del Bosque",
  "Arma de la Tormenta",
  "Arma del Dolor",
  "Arma de Combate",
  "Arma Magica",
  "Arma Sideral",
  "Arma Legendaria",
  "Arma Precaria",
  "Arma Oscura",
  "Arma del Clavel",
  "Arma de M'shong",
  "Arma de Förh",
  "Arma de Himmelzelt",
  "Arma de Tundra",
  "Arma del Ciclope",
  "Armadura de Piedra",
  "Arma de Ceniza",
  "Arma Única de Bolthemert",
  "Arma de Hielo Seco",
  "Arma de 8bits",
  "Arma Eterna y No Muerta",
  "Arma Muerta",
  "Arma Pesada",
  "Arma de Combate de Worther",
  "Arma Epica",
  "Arma Usada",
  "Arma Vieja",
  "Arma Básica",
  "Arma Rústica",
];
export const lootArrayCollar = [
  "Collar Sagrado",
  "Collar Precario",
  "Collar Mitológico",
  "Collar Forjado",
  "Collar de Hielo",
  "Collar de Fuego",
  "Collar de Viento",
  "Collar de Tierra",
  "Collar de Vdjamër",
  "Collar Renacido",
  "Collar de Cristal",
  "Collar del Pantano",
  "Collar Inmortal",
  "Collar Infinito",
  "Collar del Bosque",
  "Collar de la Tormenta",
  "Collar del Dolor",
  "Collar de Combate",
  "Collar Magico",
  "Collar Sideral",
  "Collar Legendario",
  "Collar Precario",
  "Collar Oscuro",
  "Collar del Clavel",
  "Collar de M'shong",
  "Collar de Förh",
  "Collar de Himmelzelt",
  "Collar de Tundra",
  "Collar del Ciclope",
  "Collar de Piedra",
  "Collar de Ceniza",
  "Collar Única de Bolthemert",
  "Collar de Hielo Seco",
  "Collar de 8bits",
  "Collar Eterno y No Muerto",
  "Collar Muerto",
  "Collar Pesado",
  "Collar de Combate de Worther",
  "Collar Epico",
  "Collar Usado",
  "Collar Viejo",
  "Collar Básico",
  "Collar Rústico",
];
export const lootArrayAnillo = [
  "Anillo Sagrado",
  "Anillo Precario",
  "Anillo Mitológico",
  "Anillo Forjado",
  "Anillo de Hielo",
  "Anillo de Fuego",
  "Anillo de Viento",
  "Anillo de Tierra",
  "Anillo de Vdjamër",
  "Anillo Renacido",
  "Anillo de Cristal",
  "Anillo del Pantano",
  "Anillo Inmortal",
  "Anillo Infinito",
  "Anillo del Bosque",
  "Anillo de la Tormenta",
  "Anillo del Dolor",
  "Anillo de Combate",
  "Anillo Magico",
  "Anillo Sideral",
  "Anillo Legendario",
  "Anillo Precario",
  "Anillo Oscuro",
  "Anillo del Clavel",
  "Anillo de M'shong",
  "Anillo de Förh",
  "Anillo de Himmelzelt",
  "Anillo de Tundra",
  "Anillo del Ciclope",
  "Anillo de Piedra",
  "Anillo de Ceniza",
  "Anillo Única de Bolthemert",
  "Anillo de Hielo Seco",
  "Anillo de 8bits",
  "Anillo Eterno y No Muerto",
  "Anillo Muerto",
  "Anillo Pesado",
  "Anillo de Combate de Worther",
  "Anillo Epico",
  "Anillo Usado",
  "Anillo Viejo",
  "Anillo Básico",
  "Anillo Rústico",
];
